### ISSUE TITLE
RaidGuild Request: indexed.wtf doc edits and additions

### ISSUE THREAD

**Issue by kittyslasher** [syscoin/syscoinjs-lib#1]
Hello blessed devs,
@sidhujag @dwasyluk 

We here at Raid Guild have brought you indexed.wtf and are taking care to make sure the docs we display for each Layer 2 and side-chain project are accurate and filled with information the dev teams would like to highlight specifically. Having easily accessible information about all these solutions will bring more attention to your project.

Please find the markdown for the docs for your project below.

Kindly review, edit and provide any missing details and information at your taste and discretion as project leaders.

Moving forward we aim to keep indexed.wtf as current and beneficial to developers researching the ecosystem as possible. Please feel free at any time to submit an issue or PR to update the displayed information.

Thank you for your attention to this matter.

Best,
The Indexed Army
We stand for accurate data.

www.RaidGuild.org
@chair28980 @kittyslasher

```markdown
# Syscoin Docs


## Name
Syscoin

## Description
Syscoin is a Peer-to-Peer Electronic
Cash System Built For Business Applications. Syscoin comes with a 2-way bridge for ERC-20 tokens and with ability to create custom blockchain-based tokens.



## Consensus Type
Syscoin has two consensus layers. In the first layer, Z-DAG (Zero-Confirmation Directed Acyclic Graph) is used to arrange transactions in order before being written to the blockchain. The second layer – Masternode – uses hybrid PoW/PoS model to help disseminate transactions, blocks, forks and headers in a mesh topology to promote a healthy network of full nodes.

## Tx Cost
13c USD per 10k TXs

## Average TPS
20-60k TPS burst capacity w/ ZDAG

## Finality
10 seconds on first layer. 1 minute on second layer which ensures confirmation and conflict resolution


## Governance/validator Token
$SYS

## Transactional Token
$SYS

## Resources
[Website](https://syscoin.org/whitepaper)
[Github](https://github.com/syscoin)
[Whitepaper](https://syscoin.org/syscoin3_whitepaper_summary.pdf)
[Developer Docs](https://syscoin.org/whitepaper)


## Social Media & Community
[Twitter](https://twitter.com/syscoin)
[Telegram](https://t.me/Syscoin_Official)
[Facebook](https://www.facebook.com/Syscoin/)
[Instagram](https://www.instagram.com/syscoin_org/)
[Reddit](https://www.reddit.com/r/SysCoin/)
[Youtube](https://www.youtube.com/channel/UCTx546WgFKfKQg0_814FfMA)



```

**Comment by sidhujag** [comment]
Thanks!

**Comment by kittyslasher** [comment]
> Thanks!

With the rising costs in gas and the constant need for a layer 2 solution, we are looking to get the information at indexed.wtf updated as quickly as possible. Please let me know if you have any questions!

**Comment by sidhujag** [comment]
pls read https://jsidhu.medium.com/a-design-for-an-efficient-coordinated-financial-computing-platform-ab27e8a825a0

**Comment by kittyslasher** [comment]
> pls read https://jsidhu.medium.com/a-design-for-an-efficient-coordinated-financial-computing-platform-ab27e8a825a0

I really appreciate the article. I will take some time to read throuigh this. We are busy putting together the website and ask you as the devs provide us the Information you want highlighted about your project and fill in the template provided in markdown.

**Comment by sidhujag** [comment]
ok will take a look at this this week

**Comment by kittyslasher** [comment]
> ok will take a look at this this week

We really appreciate your efforts and look forward to driving more attention to your project. We will also have a line of communication set up for future updates so as your project grows we can keep accurate information!  When you get a time to fill everything out just let me know so we can work on getting everything updated!

**Comment by kittyslasher** [comment]
> ok will take a look at this this week

Good morning/afternoon, We are going to going live the revised edition of the site within the next week. Do you feel the updated information is the most accurate information?

**Comment by sidhujag** [comment]
yes looks ok @kittyslasher
